### ISSUE TITLE
Usage documentation

### ISSUE THREAD

**Issue by jwalkerbg** [cforce/redmine_embedded_video#1]
Please give more examples of usage. Particularly I would like to know what is "YOUTUBE_URL". What is its format.

**Comment by cforce** [comment]
Usage:

{{video(<ATTACHEMENT>|<URL>|<YOUTUBE_URL>[,<width>,<height>])}}

For external urls just use the complete http url:

{{video(http://youtu.be/o9aA9wCQ9co)}}
{{video(http://youtu.be/o9aA9wCQ9co[640,480])}}

For attached videos, don't use qny path

{{video(History.flv)}}
{{video(vid.swf)}}
